### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by raiguard** [raiguard/rainmeter-settings#2]
Just a list of things to do before this will be publicly released:

- [x] Import updates from ModernGadgets
- [x] Consolidate Radio() and Input() functions (they're functionally identical)
- [x] Reorganize toggle button function to put the 'on' value before the 'off' value
- [x] Consolidate GetRadioIcon() into GetIcon() using the new value order
- [x] Add settings path and config path arguments to script measure (overrides for everything in that particular settings skin)
- [x] Reorganize settings functions to put settings and config path arguments at the end
- [ ] Add Pivot() function
- [ ] Add RainRGB() function
- [ ] Add InputText() function
- [ ] Figure out how the actual heck to write documentation
- [ ] Write the documentation
- [ ] ???
- [ ] Profit

#### Concepts
- Script Measure
- ActionSets
- IfLogic
#### Implementation
- GetIcon()
- Toggle() and Set()
- Optional path arguments
#### Example Skin

**Comment by raiguard** [comment]
So I am adding a new function called Switch(). This function will be what actually does the gruntwork, with Toggle() and Set() being easier-to-understand shortcuts for the Switch() function.

Switch() will take in a table as an argument. The table will be formatted as follows:

```
{
   variableName = {
      state1,
      state2,
      state3,
      ...
   },
   variableName2 = {
      state1,
      state2,
      state3,
      ...
   },
   ...
}
```
This format will allow the modification of multiple variables with one function call, a huge improvement from the existing one variable per function call. You can have as many variables as you wish, and those variables can have as many states as you wish (as long as they all have the same number of states, that is...). If a variable has more than one state, then the script will set it to the next one in the list. If it only has one, it will simply set it to that state always. This combines the functionality of both Toggle() and Set() into one function, and adds more capabilities to boot.

Variable state arguments will always be converted to strings, so using integers or booleans will work as well if you define them that way.

Example:  
`Switch({ customCpuName = { 0, 1 }, cpuName = { '[&*MeasureCpuDisplayName*]', '[$UserInput]' } }, 'CpuNameAction')`

Of course, Toggle() and Set() will still be available as the basic functions, with Switch() being an optional advanced method if such is required.
